In [5]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [6]:
from ucimlrepo import fetch_ucirepo

# Dataset 1: Differentiated Thyroid Cancer Recurrence

Link: https://archive.ics.uci.edu/dataset/915/differentiated+thyroid+cancer+recurrence

In [29]:
# dataset
differentiated_thyroid_cancer_recurrence = fetch_ucirepo(id=915)

# data (as pandas dataframes)
X = differentiated_thyroid_cancer_recurrence.data.features
y = differentiated_thyroid_cancer_recurrence.data.targets

In [30]:
X.head(8)

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent
5,52,M,Yes,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Indeterminate
6,41,F,No,Yes,No,Clinical Hyperthyroidism,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent
7,46,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent

## Uyarı 1:

Verisetinde "String" ifadeler "Nümerik" değerlere çevrilmeli. Çevirmeden Makine öğrenmesi yöntemlerini uygulamaya çalıştığımız için hata veriyordu.

In [31]:
# Kategorik sütunları seç
cat_cols = X.select_dtypes(include="object").columns

# String -> Integer dönüşümü
for col in cat_cols:
    X[col] = X[col].astype("category").cat.codes

/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes

In [32]:
X.head(8)

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response
0,27,0,0,0,0,2,3,3,2,1,2,0,0,0,0,2
1,34,0,0,1,0,2,1,3,2,1,2,0,0,0,0,1
2,30,0,0,0,0,2,4,3,2,1,2,0,0,0,0,1
3,62,0,0,0,0,2,4,3,2,1,2,0,0,0,0,1
4,62,0,0,0,0,2,1,3,2,0,2,0,0,0,0,1
5,52,1,1,0,0,2,1,3,2,0,2,0,0,0,0,2
6,41,0,0,1,0,0,4,3,2,1,2,0,0,0,0,1
7,46,0,0,0,0,2,4,3,2,1,2,0,0,0,0,1

## Uyarı 2:

y label değerleri de benzer şekilde Yes-No "String" ifadeler olarak verilmiş. Bunlaru da "Nümerik" değerlere yani Yes ise 1, No ise 0 olacak şekilde çevirelim.

In [42]:
y = y.replace({"No": 0, "Yes": 1})

/tmp/ipykernel_1918/727621696.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({"No": 0, "Yes": 1})

# Dataset 2: Glioma Grading Clinical and Mutation Features

Link: https://archive.ics.uci.edu/dataset/759/glioma+grading+clinical+and+mutation+features+dataset

In [53]:
# dataset
glioma_grading_clinical_and_mutation_features = fetch_ucirepo(id=759)

# data (as pandas dataframes)
X = glioma_grading_clinical_and_mutation_features.data.features
y = glioma_grading_clinical_and_mutation_features.data.targets

In [56]:
X.sample(7)

,Gender,Age_at_diagnosis,Race,IDH1,TP53,ATRX,PTEN,EGFR,CIC,MUC16,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
688,1,24.43,black or african american,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
759,1,65.39,white,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
317,0,42.85,black or african american,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
780,0,55.59,black or african american,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
743,0,51.55,white,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
66,0,52.63,white,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
834,1,77.89,white,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
y

     Grade
0        0
1        0
2        0
3        0
4        0
..     ...
834      1
835      1
836      1
837      1
838      1

[839 rows x 1 columns]

## Uyarı 1:

Race Sütununda "String" ifadeler "Nümerik" değerlere çevrilmeli. Çevirmeden Makine öğrenmesi yöntemlerini uygulamaya çalıştığımız için hata veriyordu.

In [57]:
# Kategorik sütunları seç
cat_cols = X.select_dtypes(include="object").columns

# String -> Integer dönüşümü
for col in cat_cols:
    X[col] = X[col].astype("category").cat.codes

/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes

In [59]:
X.sample(8)

,Gender,Age_at_diagnosis,Race,IDH1,TP53,ATRX,PTEN,EGFR,CIC,MUC16,...,FUBP1,RB1,NOTCH1,BCOR,CSMD3,SMARCA4,GRIN2A,IDH2,FAT4,PDGFRA
813,1,32.73,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
225,0,39.69,3,1,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
729,0,54.24,3,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23,0,66.84,3,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
576,1,45.37,3,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
717,1,75.47,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
116,0,64.00,3,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
609,1,23.36,3,0,1,1,0,1,1,1,...,1,1,0,1,1,1,1,1,1,1

# Dataset 3: Estimation of Obesity Levels Based On Eating Habits and Physical Condition

Link: https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition

In [103]:
# dataset
estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition = fetch_ucirepo(id=544)

# data (as pandas dataframes)
X = estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition.data.features
y = estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition.data.targets

In [104]:
X.sample(8)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
344,Male,18.000000,1.870000,173.000000,yes,yes,3.000000,3.000000,Frequently,no,2.000000,no,2.000000,1.000000,Sometimes,Public_Transportation
1993,Female,21.028989,1.748524,133.878843,yes,yes,3.000000,3.000000,Sometimes,no,2.868167,no,1.483720,0.835090,Sometimes,Public_Transportation
1685,Male,25.015173,1.788239,115.382519,yes,yes,1.735664,3.000000,Sometimes,no,2.041536,no,1.392406,0.391740,Sometimes,Public_Transportation
1271,Female,18.000000,1.670058,86.242679,yes,yes,2.609123,3.000000,Sometimes,no,1.955053,no,1.186013,0.000000,no,Public_Transportation
1399,Female,23.000000,1.611058,84.191125,yes,yes,2.141280,2.989112,Sometimes,no,2.519841,no,2.111370,0.013483,no,Public_Transportation
1984,Female,20.781751,1.734092,125.117633,yes,yes,3.000000,3.000000,Sometimes,no,1.542490,no,0.627700,0.450479,Sometimes,Public_Transportation
814,Male,22.283082,1.870931,89.251639,yes,yes,2.000000,2.799979,Sometimes,no,1.081333,no,0.444347,1.000000,Sometimes,Public_Transportation
1188,Female,19.005725,1.599999,73.513873,yes,no,2.942154,2.667711,Sometimes,no,2.184768,no,1.524405,0.805008,Sometimes,Public_Transportation

## Uyarı 1:

Verisetinde "String" ifadeler "Nümerik" değerlere çevrilmeli. Çevirmeden Makine öğrenmesi yöntemlerini uygulamaya çalıştığımız için hata veriyordu.

In [105]:
# Kategorik sütunları seç
cat_cols = X.select_dtypes(include="object").columns

# String -> Integer dönüşümü
for col in cat_cols:
    X[col] = X[col].astype("category").cat.codes

/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes

In [106]:
y.sample(8)

               NObeyesdad
285        Obesity_Type_I
1822     Obesity_Type_III
1008  Overweight_Level_II
263   Insufficient_Weight
1174  Overweight_Level_II
837    Overweight_Level_I
826    Overweight_Level_I
317         Normal_Weight

## Uyarı 2:

y label değerleri de benzer şekilde  "String" ifadeler olarak verilmiş. Bunları da "Nümerik" değerlere çevirelim.

In [107]:
y.value_counts()

NObeyesdad
Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: count, dtype: int64

## Uyarı 3:

Bu veri setinde Y yani "Obezite Seviyesi" yukarıda görüldüğü gibi 7 sınıfa ayrılmış. Bu tip sınıflandırmalara multiclass deniyor. Ancak bu bizim seviyemize göre biraz daha zor. Bu yüzden biz bu veriyi iki sınıflıya dönüştürelim. Obez Olmayanlar:0, Obez olanlar:1

In [108]:
y = y.replace({"Insufficient_Weight": 0,
               "Normal_Weight": 0,
               "Overweight_Level_I": 1,
               "Overweight_Level_II": 1,
               "Obesity_Type_I": 1,
               "Obesity_Type_II": 1,
               "Obesity_Type_III": 1})

/tmp/ipykernel_1918/682357979.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({"Insufficient_Weight": 0,

In [109]:
y.sample(6)

      NObeyesdad
2029           1
1047           1
1272           1
318            0
1438           1
747            1

# Dataset 4: AIDS Clinical Trials Group Study

Link: https://archive.ics.uci.edu/dataset/890/aids+clinical+trials+group+study+175

In [120]:
# dataset
aids_clinical_trials_group_study_175 = fetch_ucirepo(id=890)

# data (as pandas dataframes)
X = aids_clinical_trials_group_study_175.data.features
y = aids_clinical_trials_group_study_175.data.targets

In [121]:
X.sample(9)

,time,trt,age,wtkg,hemo,homo,drugs,karnof,oprior,z30,...,gender,str2,strat,symptom,treat,offtrt,cd40,cd420,cd80,cd820
633,1056,3,41,77.11200,0,1,0,100,0,0,...,1,0,1,0,1,0,428,570,602,590
785,1132,0,42,78.50000,0,1,0,90,0,1,...,1,1,3,0,0,0,316,425,778,1236
892,1021,0,30,83.50776,0,1,0,100,0,0,...,1,0,1,0,0,0,375,294,1054,645
1657,950,1,24,72.50000,0,0,0,80,0,0,...,0,0,1,1,1,1,347,343,1167,1300
1524,897,3,25,67.58640,0,1,0,100,0,0,...,1,0,1,0,1,1,456,413,1766,843
1755,958,3,32,67.13280,0,0,1,100,0,0,...,1,0,1,0,1,0,200,164,2720,2266
279,1122,3,28,85.50360,0,1,1,100,0,1,...,1,1,3,0,1,0,209,291,897,1435
1294,318,1,34,68.26680,0,1,0,90,0,1,...,1,1,3,0,1,1,276,142,1299,996
1269,954,0,41,83.46240,0,1,0,90,0,0,...,1,0,1,1,0,1,198,281,1859,2190

In [122]:
y.sample(9)

      cid
1829    0
1294    1
1298    0
612     0
1083    0
1613    0
1377    1
2075    0
1518    1

## Not:

Bu verisetinde önişleme yapılmış herhangi bir dönüşüm gerektirmeden doğrudan kullanılabilir.

# Dataset 5: Autistic Spectrum Disorder Screening Data for Children

Link: https://archive.ics.uci.edu/dataset/419/autistic+spectrum+disorder+screening+data+for+children

In [176]:
# dataset
autistic_spectrum_disorder_screening_data_for_children = fetch_ucirepo(id=419)

# data (as pandas dataframes)
X = autistic_spectrum_disorder_screening_data_for_children.data.features
y = autistic_spectrum_disorder_screening_data_for_children.data.targets

In [177]:
X.sample(7)

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,ethnicity,jaundice,autism,country_of_res,used_app_before,result,age_desc,relation
75,0,0,0,1,1,1,1,1,1,0,5.0,m,White-European,no,no,'United Kingdom',no,6,'4-11 years',Parent
252,1,0,1,0,1,1,1,1,0,1,7.0,m,'Middle Eastern ',yes,no,Jordan,no,7,'4-11 years',Parent
151,1,0,1,0,1,1,0,1,1,1,4.0,m,Black,no,yes,'United States',no,7,'4-11 years',Parent
201,1,1,1,1,1,1,1,0,1,0,4.0,f,White-European,no,yes,'United Kingdom',no,8,'4-11 years',Parent
159,1,1,1,1,1,1,1,1,1,1,8.0,m,White-European,no,no,'United Kingdom',no,10,'4-11 years',Parent
115,1,1,1,1,1,1,1,1,1,1,11.0,m,Asian,yes,no,India,no,10,'4-11 years',Relative
160,1,0,1,1,1,1,0,1,0,1,11.0,m,NaN,no,no,Jordan,no,7,'4-11 years',NaN

## Uyarı 1:

Verisetinde "String" ifadeler "Nümerik" değerlere çevrilmeli. Çevirmeden Makine öğrenmesi yöntemlerini uygulamaya çalıştığımız için hata veriyordu.

In [178]:
# Kategorik sütunları seç
cat_cols = X.select_dtypes(include="object").columns

# String -> Integer dönüşümü
for col in cat_cols:
    X[col] = X[col].astype("category").cat.codes

/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes
/tmp/ipykernel_1918/4147738001.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = X[col].astype("category").cat.codes

In [179]:
y.sample(5)

    class
266    NO
94    YES
205    NO
145   YES
177   YES

## Uyarı 2:

y label değerleri de benzer şekilde Yes-No "String" ifadeler olarak verilmiş. Bunlaru da "Nümerik" değerlere yani Yes ise 1, No ise 0 olacak şekilde çevirelim.

In [163]:
y = y.replace({"NO": 0, "YES": 1})

/tmp/ipykernel_1918/1269542874.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y = y.replace({"NO": 0, "YES": 1})

## Uyarı 3:

Bu veri setinde diğer verilerden farklı olarak Eksik Veri mevcut. Veri setindeki bazı veriler bilinmediği ve boş olduğu için modellerimiz hata veriyor. Eksik değerler aşağıda görüldüğü üzere sadece 4 adet ve age sütununda. Sayıca az olduğu için bu eksik örnekleri veri setinden atarak, bu sorundan kurtulabiliriz.

In [164]:
print(X.isnull().sum())

A1_Score           0
A2_Score           0
A3_Score           0
A4_Score           0
A5_Score           0
A6_Score           0
A7_Score           0
A8_Score           0
A9_Score           0
A10_Score          0
age                4
gender             0
ethnicity          0
jaundice           0
autism             0
country_of_res     0
used_app_before    0
result             0
age_desc           0
relation           0
dtype: int64

In [165]:
# X deki Nan değerleri ve y de buna karşılık gelen etiketleri kaldır.

mask = X.notnull().all(axis=1)

X = X[mask]
y = y[mask]